### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Kuree** [Kuree/hermes#1]
This is a potential TODO list. Not everything on this list will get implemented:

~~- [ ] `_common_metadata` for partitioned datasets~~
~~- [ ] column index.~~

- [x] multiple topics for tracker
- [x] events caching
- [ ] performance model support
    - [x] feed inputs
    - [ ] correlation
- [x] use parquet column statistics
- [ ] bloom filter to speed up transaction materization
- [x] filesystem
- [x] Transaction groups (transactions of transactions)
- [x] Add name to event and event/transaction/group
- [x] RTL parsing for enums
- [ ] More fine-grained event loading
